### ISSUE TITLE
[Feature Request] Download speed & Time remain indicator within the downloads page

### ISSUE THREAD

**Issue by AdenMGB** [Drop-OSS/drop-app#7]
### **Hello**, I think a nice little to have QoL feature would be Download speed & Time remain indicator when downloading apps from the target server via the drop client app

I'd imagine this is quite and easy little feature to add, so much so I have already wrote the code for it and planning on becoming a contributor, but I cannot test it because for some reason when I run `yarn tauri dev` I get this weird  `ERROR  [unhandledRejection] require is not defined` but oh well that's for another day.

Thanks for maintaining this awesome little project!

_Sincerely, Aden_

Just in case you wanted it here's my implementation which is yet to be confirmed working with the files:
[new code.zip](https://github.com/user-attachments/files/18256024/new.code.zip)

### pages\settings\downloads.vue

![image](https://github.com/user-attachments/assets/9b07fdd8-adce-4b91-bc3c-f47aa8ecc8a2)
![image](https://github.com/user-attachments/assets/793c5593-7885-4879-b734-f28ced9a290d)
![image](https://github.com/user-attachments/assets/f1e9e48c-a917-40da-a2b8-e6525c89ceeb)

### utils\format.ts (new file)

![image](https://github.com/user-attachments/assets/601f4ee7-5d13-48c1-a1c7-d5e5fe596c61)

### src-tauri\src\downloads\progress_object.rs

![image](https://github.com/user-attachments/assets/60fe8e65-9482-4ea6-8d63-2de2dc51ee53)

**Comment by DecDuck** [comment]
Oh shit I thought would've been a pain in the ass to implement, I completely forgot our progress track just counted bytes. This feature was definitely planned, but I had been putting it off. Good to know it'll be since and easy!

We had initially planned to push events from the Rust side to update download statistics on the frontend, but this might be a better solution. @quexeky ?

**Comment by DecDuck** [comment]
Not pushed yet. Still adding the final touches.

**Comment by DecDuck** [comment]
Event based.
