### ISSUE TITLE
[Feature Request] Quick discord button link next to profile dropdown

### ISSUE THREAD

**Issue by Sortedsheep0101** [Drop-OSS/drop-app#8]
### **Just a small lil' idea to have quick access to the community discord maybe**
Had the same issue as AdenMGB where I couldn't run `yarn tauri dev` but if there is something wrong, ehh oh well.

I had downloaded a template of the discord icon and just put it somewhere where it fits.

First time using Vue btw, so expect for it to be retarded.

**components/Header.vue**
![image](https://github.com/user-attachments/assets/4b7ad4a8-b38f-4e0e-b8d2-1fa61cf571d5)

![image](https://github.com/user-attachments/assets/fb53cfcb-472b-490c-9972-66a570a58cd5)

**components/icons/DiscordIcon.vue (new Script + new SVG)**
![image](https://github.com/user-attachments/assets/3c377077-0553-4fbe-81b4-ebe8ccbe4e7d)

Yours Truly,
Sortedsheep0101

**Comment by DecDuck** [comment]
By the way, that error doesn't mean the dev environment failed to start, it's just something annoying that TailwindCSS does. 

@AdenMGB 

For the Discord icon, we already include it on error pages (for obvious reasons lmao), so I'm hesitant to include to elsewhere, especially somewhere so prominent. Maybe somewhere in the app settings?

**Comment by Sortedsheep0101** [comment]
yeah that seems abt right
do what you want to do, good luck!
